### ISSUE TITLE
Different header for every reconnect

### ISSUE THREAD

**Issue by twonky4** [launchdarkly/okhttp-eventsource#59]
I have a JWT Token in my header to authenticate my request. The token is maybe outdated and have to be changed for a reconnect.

Is this currently possible or should I create a Pull Request?

I currently use it like this:
```MyEventHandler eventHandler = new MyEventHandler();

Headers headers = new Headers.Builder().add("Authorization", "Bearer " + tokenService.getAccessToken()).build();

EventSource.Builder builder = new EventSource.Builder(eventHandler, URI.create(url))
        .headers(headers);

EventSource eventSource = builder.build();
eventSource.start();
```

I'm looking for a Solution like this:

```
MyEventHandler eventHandler = new MyEventHandler();

EventSource.Builder builder = new EventSource.Builder(eventHandler, URI.create(url))
    .headerBuilder(() -> {
        return new Headers.Builder().add("Authorization", "Bearer " + tokenService.getAccessToken()).build();
    });

    EventSource eventSource = builder.build();
    eventSource.start();
```

**Comment by eli-darkly** [comment]
There is not currently a way to provide a header factory function, rather than a fixed set of headers.

**Comment by twonky4** [comment]
Yeah like I thought. Is there a plan for?

Does it make sense if I create a Pull Request or do you think such a feature is not worth to implement?

**Comment by eli-darkly** [comment]
@twonky4 Well, no we did not have a plan for adding this, because until now we had no indication that anyone wanted such a feature. It's not out of the question to add such a feature, even if demand for it is very small, but I would prefer to be sure first that there's no other way to accomplish your goal— so as not to clutter up the EventSource library with redundant functionality that isn't related to its primary purpose.

Doesn't OkHttp allow you to configure a client with an interceptor that can modify each outgoing request, as shown [here](https://gist.github.com/lfmingo/768a29eafc4a9d25d75ef31e2be506f7)? If so, you should be able to attach your own logic for setting any desired headers on a per-request basis, and then pass your pre-configured client to EventSource with `EventSource.Builder.client()`.

**Comment by twonky4** [comment]
Yeah, makes absolute sense. I will look for a workaround tomorrow. If it's possible I will post a solution here and close the issue.

**Comment by twonky4** [comment]
yeah. my solution would look like:
```
MyEventHandler eventHandler = new MyEventHandler();

OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
httpClient.addInterceptor(chain -> {
    Request original = chain.request();

    Request request = original.newBuilder()
            .header(AUTHORIZATION, "Bearer " + tokenService.getAccessToken())
            .build();

    return chain.proceed(request);
});

EventSource.Builder builder = new EventSource.Builder(eventHandler, URI.create(url))
    .client(httpClient.build());

EventSource eventSource = builder.build();
eventSource.start();
```
