### ISSUE TITLE
[ClassNotFoundException] Didn't find class "java.time.Duration"

### ISSUE THREAD

**Issue by Nghicv** [launchdarkly/okhttp-eventsource#64]
Stacktrace
com.launchdarkly.eventsource.EventSource$Builder.<init> (EventSource.java:499)
com.launchdarkly.eventsource.EventSource$Builder.<init> (EventSource.java:525)

**Comment by gwhelanLD** [comment]
Hi @Nghicv,

The `java.time.Duration` API is provided by the Java implementation. Getting a `ClassNotFoundException` for this class is likely because the Java implementation is old enough that it does not support the API. `Duration` should be available in compliant Java 8 implementations and Android API levels 26 and later. All versions of `okhttp-eventsource` after https://github.com/launchdarkly/okhttp-eventsource/releases/tag/2.0.0 require Java 8. If you require Java 7 or earlier Android API level support, please use the latest 1.x release (https://github.com/launchdarkly/okhttp-eventsource/releases/tag/1.11.2).

Thanks,
@gwhelanLD

**Comment by Nghicv** [comment]
@gwhelanLD 
Thank you. 
I am using min SDK version 21 and java 8. is it ok to use version 1.11.2?

**Comment by choongyouqi** [comment]
you can use the latest version of okhttp-eventsource. just add the desugaring lib to your project

https://developer.android.com/studio/write/java8-support-table
