### ISSUE TITLE
jitpack builds failed

### ISSUE THREAD

**Issue by rwst** [launchdarkly/okhttp-eventsource#66]
It is not possible to get your code from jitpack.io, e.g. https://jitpack.io/com/github/launchdarkly/okhttp-eventsource/2.5.0/build.log

Do you recommend including your source directly?

**Comment by eli-darkly** [comment]
Is the regular Maven repository not an option? That is where we publish it. We have never published to Jitpack.

**Comment by eli-darkly** [comment]
Actually, looking again at the docs for Jitpack (which I wasn't familiar with), their headline "publish your JVM and Android libraries" is a little misleading since it looks like this is not a repository we _could_ publish anything to— instead it's a "build it for you" service that pretends to be a repository. It's meant to be used with projects that do _not_ publish any already-built artifacts. But we do— we publish them to Maven: https://search.maven.org/artifact/com.launchdarkly/okhttp-eventsource

**Comment by eli-darkly** [comment]
By the way, the reason Jitpack fails to build this package is that our build includes a code-signing step. For obvious reasons, Jitpack does not have a copy of our code-signing key.
